function totalQty(){return Object.values(state.cart).reduce((e,a)=>e+a,0)}
function pricePlan(e=totalQty()){return e<=5?{unit:65,label:"Precio de menú",band:"1–5 piezas",event:!1,confirmed:!0}:e<=20?{unit:60,label:"Precio por pedido",band:"6–20 piezas",event:!1,confirmed:!0}:e<=50?{unit:55,label:"Precio por volumen",band:"21–50 piezas",event:!1,confirmed:!0}:e<=99?{unit:53,label:"Estimado de evento",band:"51–99 piezas",event:!0,confirmed:!1}:e<=149?{unit:52,label:"Estimado de evento",band:"100–149 piezas",event:!0,confirmed:!1}:{unit:50,label:"Estimado de evento",band:"150+ piezas",event:!0,confirmed:!1}}
function baseUnitPrice(e=totalQty()){return pricePlan(e).unit}
function personalizationSurcharge(){return"phrase"===state.personalization?10:"logo"===state.personalization?12:0}
function deliveryEstimate(){return"delivery"===state.fulfillment?Number(state.shippingFee||0):0}
function totalEstimate(){const e=totalQty();return e*(baseUnitPrice(e)+personalizationSurcharge())+deliveryEstimate()}
function money(e){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(e)}
function cartItems(){return Object.entries(state.cart).filter(([,e])=>e>0).map(([e,a])=>({...byId(e),qty:a}))}
function hasAlcohol(){return cartItems().some(e=>e.alcohol)}
function theme(e){return THEMES[e]||"#dfe7ef"}
function progressInfo(e=totalQty()){return e<6?{text:`Agrega ${6-e} ${6-e==1?"bebida":"bebidas"} para activar $60 c/u.`,pct:e/6*25}:e<21?{text:`Te ${21-e==1?"falta":"faltan"} ${21-e} para activar $55 c/u.`,pct:25+(e-6)/15*35}:e<51?{text:`Con ${51-e} más, tu pedido entra a precio de evento.`,pct:60+(e-21)/30*25}:e<100?{text:"Tu pedido ya está en tarifa estimada de evento. Confirmamos fecha, sabores y logística por WhatsApp.",pct:88}:e<150?{text:"Por el volumen, el estimado baja a $52 c/u. La cotización final se confirma contigo.",pct:95}:{text:"Este pedido entra al último escalón de evento: estimado de $50 c/u.",pct:100}}
function showToast(e){const a=$("#toast");a.textContent=e,a.classList.add("show"),clearTimeout(showToast.timer),showToast.timer=setTimeout(()=>a.classList.remove("show"),2200)}
function renderOccasions(){$("#occasionStrip").innerHTML=OCCASIONS.map(e=>`<button class="occasion-card" data-occasion="${e.id}"><span class="occasion-icon">${icon(e.icon)}</span><span><b>${e.title}</b><small>${e.copy}</small></span></button>`).join(""),$$("[data-occasion]").forEach(e=>e.onclick=()=>{state.occasion=e.dataset.occasion,showScreen("menu"),showToast("Perfecto. Ahora arma tu mix.")})}
function productMarkup(e,a=!1){return a?`<button class="mini-product" data-product="${e.id}" style="background:${theme(e.id)}"><div class="mini-product-media"><img src="${e.image}" alt="${e.name}"></div><b>${e.name}</b><small>${e.friendly}</small></button>`:`<article class="product-card reveal" data-product="${e.id}" style="background:${theme(e.id)}"><button class="add-circle" aria-label="Agregar ${e.name}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M12 5v14M5 12h14"/></svg></button>${e.alcohol?'<span class="alcohol-mark">Con alcohol</span>':""}<div class="media"><img src="${e.image}" alt="${e.name}"></div><div class="product-info"><span class="product-name">${e.name}</span><span class="product-note">${e.friendly}</span></div></article>`}
function renderCollection(e,a){const t=$(e);t&&(t.innerHTML=a.map(e=>productMarkup(byId(e),!0)).join(""),attachProductClicks(t))}
function renderFeatured(){renderCollection("#featuredStrip",["espresso-horchata","mojito-mariposa","pepino-limon","clericot"]),renderCollection("#eventStrip",["clericot","mezcalita-jamaica","mojito-clasico","maracuya-limon"]),renderCollection("#zeroStrip",["pepino-limon","jamaica-limon","horchata","maracuya-limon"])}
function renderCategories(){$("#categoryChips").innerHTML=CATEGORIES.map(e=>`<button class="chip ${state.category===e.id?"active":""}" data-cat="${e.id}">${e.label}</button>`).join(""),$$("[data-cat]").forEach(e=>e.onclick=()=>{state.category=e.dataset.cat,renderCategories(),renderMenu()})}
function renderMenu(){const e=state.search.trim().toLowerCase(),a=PRODUCTS.filter(a=>("all"===state.category||a.category===state.category)&&(!e||`${a.name} ${a.description} ${a.friendly}`.toLowerCase().includes(e)));$("#productGrid").innerHTML=a.length?a.map(e=>productMarkup(e)).join(""):'<div style="grid-column:1/-1;padding:45px 10px;text-align:center;color:var(--muted)">No encontramos esa bebida. Prueba con otro sabor.</div>',attachProductClicks($("#productGrid"))}
function attachProductClicks(e){e.querySelectorAll("[data-product]").forEach(e=>e.onclick=a=>{a.preventDefault(),openProduct(e.dataset.product)})}
function openProduct(e){state.sheetProduct=e,state.sheetQty=1,renderSheet(),$("#sheetBackdrop").classList.add("open"),$("#productSheet").classList.add("open")}
function closeSheet(){$("#sheetBackdrop").classList.remove("open"),$("#productSheet").classList.remove("open")}
function projectedPrice(){return baseUnitPrice(totalQty()+state.sheetQty)}
function renderSheet(){const e=byId(state.sheetProduct);if(!e)return;const a=pricePlan(totalQty()+state.sheetQty),t=a.unit*state.sheetQty,o=a.event?"Estimado por volumen de evento. Confirmamos el total final contigo.":"Este precio se aplica a todas las bebidas del pedido.";$("#sheetContent").innerHTML=`<div class="sheet-media" style="background:${theme(e.id)}"><button class="sheet-close" id="sheetClose"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg></button><span class="sheet-tag">${e.categoryLabel}</span><img src="${e.image}" alt="${e.name}"></div><div class="sheet-body"><h2>${e.name}</h2><p>${e.description} ${e.friendly}</p><div class="sheet-price"><div><small>${a.label}<br>${o}</small></div><strong>$${a.unit} c/u</strong></div><div class="sheet-controls"><b>¿Cuántas agregamos?</b><div class="large-stepper"><button id="sheetMinus">−</button><span>${state.sheetQty}</span><button id="sheetPlus">+</button></div></div><button class="sheet-add" id="sheetAdd"><span>Agregar al pedido</span><span>${money(t)}</span></button></div>`,$("#sheetClose").onclick=closeSheet,$("#sheetMinus").onclick=()=>{state.sheetQty=Math.max(1,state.sheetQty-1),renderSheet()},$("#sheetPlus").onclick=()=>{state.sheetQty=Math.min(300,state.sheetQty+1),renderSheet()},$("#sheetAdd").onclick=()=>{state.cart[e.id]=(state.cart[e.id]||0)+state.sheetQty,updateCartUI(!0),closeSheet(),showToast(`${state.sheetQty} ${1===state.sheetQty?"bebida agregada":"bebidas agregadas"}.`)}}
function updateCartUI(e=!1){const a=totalQty();$("#cartCount").textContent=a,$("#cartCount").classList.toggle("show",a>0),$("#navCartDot").classList.toggle("show",a>0),e&&($("#topCart").classList.remove("bump"),$("#topCart").offsetWidth,$("#topCart").classList.add("bump")),renderCart(),"checkout"===state.screen&&renderCheckout()}
function changeItem(e,a){state.cart[e]=Math.max(0,(state.cart[e]||0)+a),state.cart[e]||delete state.cart[e],updateCartUI()}